name: CADD-environment
channels:
    - conda-forge
    - tmap

dependencies:
    - python>=3.6
    - jupyterlab
    - tmap
    - faerun
    - mhfp
    - jupyter_contrib_nbextensions
    - pip:
        - pandas

